export const data = [
    {
        trackingID: "#20462",
        product: "Hat",
        customer: "Matt Dickeerson",
        date: "13/05/2022",
        amount: "$4.89",
        paymentMode: "Transfer Bank",
        status: "delivered",
        action: "edit",
    },
    {
        trackingID: "#18933",
        product: "Laptop",
        customer: "Wicktoria",
        date: "22/02/2022",
        amount: "$890",
        paymentMode: "Cash on Delivery",
        status: "delivered",
        action: "edit",
    },
    {
        trackingID: "#45169",
        product: "Phone",
        customer: "Tricky Byd",
        date: "15/06/2022",
        amount: "$300.45",
        paymentMode: "Cash on Delivery",
        status: "process",
        action: "edit",
    },
    {
        trackingID: "#34304",
        product: "Bag",
        customer: "Brad Meson",
        date: "06/09/2022",
        amount: "$899.25",
        paymentMode: "Transfer bank",
        status: "process",
        action: "edit",
    },
    {
        trackingID: "#17188",
        product: "Headset",
        customer: "Sanderson",
        date: "25/09/2022",
        amount: "$29.25",
        paymentMode: "Cash on delivery",
        status: "cancelled",
        action: "edit",
    },
    {
        trackingID: "#73003",
        product: "Mouse",
        customer: "Jun Renderfun",
        date: "04/10/2022",
        amount: "$54.95",
        paymentMode: "Transfer Bank",
        status: "delivered",
        action: "edit",
    },
    {
        trackingID: "#58825",
        product: "Clock",
        customer: "Miriam Kidd",
        date: "17/10/2022",
        amount: "$174.95",
        paymentMode: "Transfer Bank",
        status: "delivered",
        action: "edit",
    },
    {
        trackingID: "#44122",
        product: "T-shirt",
        customer: "Dominic",
        date: "24/10/2022",
        amount: "$249.95",
        paymentMode: "Cash on delivery",
        status: "delivered",
        action: "edit",
    },
    {
        trackingID: "#89094",
        product: "Monitor",
        customer: "Shanice",
        date: "01/11/2022",
        amount: "$899.95",
        paymentMode: "Transfer bank",
        status: "cancelled",
        action: "edit",
    },
    {
        trackingID: "#85225",
        product: "Keyboard",
        customer: "Poppy rose",
        date: "22/11/2022",
        amount: "$6.948",
        paymentMode: "Transfer bank",
        status: "process",
        action: "edit",
    },
]